  install:
    needs: meta
    strategy:
      fail-fast: false
      matrix:
        # Use 'include' for a clear and explicit configuration for each OS/Arch combination
        include:
          - runner: windows-latest
            os_name: win
            arch: x86_64
          - runner: windows-latest
            os_name: win
            arch: aarch64
          - runner: ubuntu-latest
            os_name: linux
            arch: x86_64
          - runner: ubuntu-latest
            os_name: linux
            arch: aarch64
          - runner: macos-latest
            os_name: osx
            arch: x86_64
          - runner: macos-latest
            os_name: osx
            arch: aarch64
            
    # Use the 'runner' from the matrix to set the correct OS for each job
    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      # 1. ADD THIS STEP to download the required dependency first.
      - name: Download MaaFramework
        uses: robinraju/release-downloader@v1
        with:
          repository: MaaXYZ/MaaFramework
          fileName: "MAA-${{ matrix.os_name }}-${{ matrix.arch }}*"
          latest: true
          out-file-path: "deps" # Download to the 'deps' folder as the script expects
          extract: true

      # 2. Your install script will now run successfully.
      - name: Install Python Script
        shell: bash
        run: |
          python ./install.py ${{ needs.meta.outputs.tag }}

      # 3. Download the UI framework. Note the corrected filename logic.
      - name: Download MFA
        uses: robinraju/release-downloader@v1
        with:
          repository: SweetSmellFox/MFAAvalonia
          # The MFAAvalonia release uses 'macos' (not 'osx') and 'arm64'/'x64' (not 'aarch64'/'x86_64').
          # We use expressions to map our matrix variables to the correct names.
          fileName: "MFAAvalonia-*-${{ matrix.os_name == 'osx' && 'macos' || matrix.os_name }}-${{ matrix.arch == 'aarch64' && 'arm64' || 'x64' }}*"
          latest: true
          out-file-path: "MFAAvalonia"
          extract: true

      - name: Install MFAAvalonia
        shell: bash
        run: |
          rm -rf MFAAvalonia/resource/base/model
          cp -r MFAAvalonia/* install

      - uses: actions/upload-artifact@v4
        with:
          name: MaaXXX-${{ matrix.os_name }}-${{ matrix.arch }}
          path: "install"